# Site settings
title: apt-get install hckrmoon
email: hckrmoon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Seoul, South Korea. A web developer with fonder of JavaScript and FP.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: youngmmmoon
github_username:  hckrmoon

# Build settings
markdown: kramdown
